# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-23 16:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        ('auth', '0007_alter_validators_add_error_messages'),
        ('mail', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='messages',
            field=models.ManyToManyField(related_name='received_by', to='mail.Message'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
    ]
